import { PhotoProps } from "@/types";

const chicagoStreetArray: PhotoProps[] = [
	{
		imageSrc: "/chicago7.JPG",
		imageAlt: "Group of skaters in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/3.2 • 1/1000 • 9mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Street"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago4.jpg",
		imageAlt: "The Chicago theater",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/320 • 47.86mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Street"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicagoEyes2.JPG",
		imageAlt: "close up of eyes on a building in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/500 • 71.52mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/protest2.JPG",
		imageAlt: "A protestor with a blindfold and sign in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/6400 • 27.44mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Street"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/pigeon.JPG",
		imageAlt: "Pigeon in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/10000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/protest.JPG",
		imageAlt: "A protestor with a blindfold in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/25600 • 50.65mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Street"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago.JPG",
		imageAlt: "Close up of an American flag on a building in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/2000 • 72mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago2.JPG",
		imageAlt: "Close up of a clock tower in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/1000 • 72mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago3.JPG",
		imageAlt: "chicago",
		description: "View of buildings in Chicago",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/3.5 • 1/2500 • 13.29mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago5.JPG",
		imageAlt: "Backlit view of birds flying in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/3.2 • 1/1600 • 9mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape, Animals"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicago6.JPG",
		imageAlt: "Silhouette of birds flying in Chicago, with one in the center",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/3.2 • 1/2500 • 9mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape, Animals"],
		index: 0,
		filtered: false,
	},
	{
		imageSrc: "/chicagoEyes.JPG",
		imageAlt: "Eyes on a building in Chicago",
		description: "",
		collection: "chicagoStreet",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/2000 • 71.03mm • ISO250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
		filtered: false,
	},
];

export default chicagoStreetArray;
