import { PhotoProps } from "@/types";

const connectArray: PhotoProps[] = [
	{
		imageSrc: "/connect/camera2.jpg",
		imageAlt: "Taking a photo of myself in a shiny orb",
		description: "",
		collection: "connect",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/camera4.jpg",
		imageAlt: "Taking a photo of myself in the Bean in Chicago",
		description: "",
		collection: "connect",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/camera3.jpg",
		imageAlt: "Recording a rainstorm",
		description: "",
		collection: "connect",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/camera.jpg",
		imageAlt: "Pentax K1000 film camera",
		description: "",
		collection: "connect",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/first2.jpg",
		imageAlt: "Kid outside",
		description: "",
		collection: "connect",
		stats: "VTech Kidizoom • 0.3MP • 640 x 480",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/first.JPG",
		imageAlt: "Kid inside",
		description: "",
		collection: "connect",
		stats: "VTech Kidizoom • 0.3MP • 640 x 480",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/first3.jpg",
		imageAlt: "My old artwork on a sticky note",
		description: "",
		collection: "connect",
		stats: "VTech Kidizoom • 0.3MP • 640 x 480",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/connect/first4.jpg",
		imageAlt: "A bunny sticker I really liked",
		description: "",
		collection: "connect",
		stats: "VTech Kidizoom • 0.3MP • 640 x 480",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
];

export default connectArray;
