import { PhotoProps } from "@/types";

const ducksAndLiliesArray: PhotoProps[] = [
	{
		imageSrc: "/ducks-and-lilies/waterLily.JPG",
		imageAlt: "white water lily",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/2000 • 63.55mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily2.JPG",
		imageAlt: "two white water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/25600 • 72.00mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck.JPG",
		imageAlt: "baby duck swimming in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.6 • 1/16000 • 71.25mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck2.JPG",
		imageAlt: "baby duck swimming in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily3.JPG",
		imageAlt: "four purple water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.0 • 1/20000 • 34.64mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily6.JPG",
		imageAlt: "one bright pink water lily",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/20000 • 50.65mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily4.JPG",
		imageAlt: "one pink water lily",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/20000 • 72.00mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily5.JPG",
		imageAlt: "three pink water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/20000 • 50.65mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily9.JPG",
		imageAlt: "one pink water lily",
		description: "one pink wa,ter lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.0 • 1/16000 • 33.98mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily10.JPG",
		imageAlt: "one pink water lily, blooming",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.0 • 1/16000 • 33.98mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck3.JPG",
		imageAlt: "baby duck moving around in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck4.JPG",
		imageAlt: "baby duck looking at lilypads in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 40.37mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily12.JPG",
		imageAlt: "one white water lily with pink tips",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/5000 • 69.49mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duckTri.JPG",
		imageAlt: "baby duck swimming in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily7.JPG",
		imageAlt: "three magenta water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/8.0 • 1/8000 • 30.26mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily8.JPG",
		imageAlt: "two pink water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/5.0 • 1/8000 • 65.97mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily13.JPG",
		imageAlt: "two white water lilies",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/8.0 • 1/1250 • 34.64mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/waterLily14.JPG",
		imageAlt: "two white water lilies, up close",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/8.0 • 1/1250 • 71.03mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck5.JPG",
		imageAlt: "baby duck swimming across water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/5.0 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck6.jpg",
		imageAlt: "duck swimming in water, looking forwards",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/ducks-and-lilies/duck7.JPG",
		imageAlt: "duck standing in water",
		description: "water lily",
		collection: "ducksAndLilies",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72.00mm • ISO3200",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
];

export default ducksAndLiliesArray;
