import { PhotoProps } from "@/types";

const excelsiorBirdsBeesArray: PhotoProps[] = [
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees.JPG",
		imageAlt: "Goose walking towards camera",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/5 • 1/16000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees5.JPG",
		imageAlt: "Goose opening beak as other geese in background eat",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/5 • 1/12800 • 53.6mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees2.JPG",
		imageAlt: "Shot of dragonfly with blurred background",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/5 • 1/16000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees3.JPG",
		imageAlt: "Close up shot of dragonfly",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees6.JPG",
		imageAlt: "Goose in foreground with four geese eating in background",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/12800 • 69.49mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees4.JPG",
		imageAlt: "Shot of several geese by the water and a bench",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/7.1 • 1/12800 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees14.JPG",
		imageAlt: "Long purple flowers in the tall grass",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4 • 1/32000 • 20.69mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees13.JPG",
		imageAlt: "Several bees on a pink flower",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/f • 1/32000 • 20.69mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees12.JPG",
		imageAlt: "Bee on long purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 49.7mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees11.JPG",
		imageAlt: "Mixed focus shot of long purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 60.05mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees21.JPG",
		imageAlt: "Bees on long white and purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/4000 • 16.86mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees8.JPG",
		imageAlt: "Duck pulling head out of the water with visible water droplets",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/8 • 1/12800 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees16.JPG",
		imageAlt: "Shot of small red sailboat, Red Ink, in the water and centered",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4 • 1/32000 • 9mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees20.JPG",
		imageAlt: "Glass reflecting the flowers and water",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees15.JPG",
		imageAlt: "Shot of small red sailboat, Red Ink, in the water framed by the trees",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 34.64mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees7.JPG",
		imageAlt: "Duck sitting still in the water",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/7.1 • 1/12800 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees9.JPG",
		imageAlt: "Duck facing away from camera",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/7.1 • 1/12800 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees10.JPG",
		imageAlt: "Duck diving into the water, with its backside up in the air",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/7.1 • 1/12800 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape"],
		index: 0,
	},

	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees17.JPG",
		imageAlt: "The last three ducks in a line of five ducks",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees19.JPG",
		imageAlt: "A line of five ducks swimming in the water",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 46.97mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/excelsior-birds-bees/birdsAndBees18.JPG",
		imageAlt: "The first three ducks in a line of five ducks",
		description: "",
		collection: "excelsiorBirdsBees",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/32000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
];

export default excelsiorBirdsBeesArray;
