interface PhotoModalProps {
	imageSrc: string;
	imageAlt: string;
	description: string;
	collection: string;
	showLink: boolean;
	stats: string;
	classAdjustments: string;
	tags?: string[];
}

const excelsiorBirdsBeesArray: PhotoModalProps[] = [
	{
		imageSrc: "/birdsAndBees.JPG",
		imageAlt: "Goose walking towards camera",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees5.JPG",
		imageAlt: "Goose opening beak as other geese in background eat",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees2.JPG",
		imageAlt: "Shot of dragonfly with blurred background",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees3.JPG",
		imageAlt: "Close up shot of dragonfly",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees6.JPG",
		imageAlt: "Goose in foreground with four geese eating in background",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees4.JPG",
		imageAlt: "Shot of several geese by the water and a bench",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape"],
	},
	{
		imageSrc: "/birdsAndBees14.JPG",
		imageAlt: "Long purple flowers in the tall grass",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
	},
	{
		imageSrc: "/birdsAndBees13.JPG",
		imageAlt: "Several bees on a pink flower",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
	},
	{
		imageSrc: "/birdsAndBees12.JPG",
		imageAlt: "Bee on long purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
	},
	{
		imageSrc: "/birdsAndBees11.JPG",
		imageAlt: "Mixed focus shot of long purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
	},
	{
		imageSrc: "/birdsAndBees21.JPG",
		imageAlt: "Bees on long white and purple flowers",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants", "Animals"],
	},
	{
		imageSrc: "/birdsAndBees8.JPG",
		imageAlt: "Duck pulling head out of the water with visible water droplets",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees16.JPG",
		imageAlt: "Shot of small red sailboat, Red Ink, in the water and centered",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/birdsAndBees20.JPG",
		imageAlt: "Glass reflecting the flowers and water",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: [""],
	},
	{
		imageSrc: "/birdsAndBees15.JPG",
		imageAlt: "Shot of small red sailboat, Red Ink, in the water framed by the trees",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/birdsAndBees7.JPG",
		imageAlt: "Duck sitting still in the water",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees9.JPG",
		imageAlt: "Duck facing away from camera",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape"],
	},
	{
		imageSrc: "/birdsAndBees10.JPG",
		imageAlt: "Duck diving into the water, with its backside up in the air",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Landscape"],
	},

	{
		imageSrc: "/birdsAndBees17.JPG",
		imageAlt: "The last three ducks in a line of five ducks",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees19.JPG",
		imageAlt: "A line of five ducks swimming in the water",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/birdsAndBees18.JPG",
		imageAlt: "The first three ducks in a line of five ducks",
		description: "",
		collection: "excelsiorBirdsBees",
		showLink: false,
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
	},
];

export default excelsiorBirdsBeesArray;
