import { PhotoProps } from "@/types";

const halfaliveArray: PhotoProps[] = [
	{
		imageSrc: "/halfalive.jpg",
		imageAlt: "concert photo",
		description: "",
		collection: "halfalive",
		stats: "Samsung S22 Ultra • f/2.4 • 1/35 • 7.9mm • ISO320",
		classAdjustments: "col-span-3 md:col-span-2 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet.gif",
		imageAlt: "concert photo",
		description: "",
		collection: "halfalive",
		stats: "Samsung S22 Ultra • f/4.9 • 1/35 • 27.2mm • ISO1250",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet3.jpg",
		imageAlt: "concert photo",
		description: "",
		collection: "halfalive",
		stats: "Samsung S22 Ultra • f/2.4 • 1/60 • 7.9mm • ISO125",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet4.jpg",
		imageAlt: "concert photo",
		description: "",
		collection: "halfalive",
		stats: "Samsung S22 Ultra • f/4.9 • 1/30 • 27.2mm • ISO320",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	// {
	// 	imageSrc: "/phoebeBridgers.jpg",
	// 	imageAlt: "concert photo",
	// 	description: "",
	// 	collection: "halfalive",
	// 	stats: "Samsung S22 Ultra • ",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["Concert"],
	// 	index: 0,
	// },
	// {
	// 	imageSrc: "/julienBaker.jpg",
	// 	imageAlt: "concert photo",
	// 	description: "",
	// 	collection: "halfalive",
	// 	stats: "Samsung S22 Ultra • ",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["Concert"],
	// 	index: 0,
	// },
	// {
	// 	imageSrc: "/lucyDacus.jpg",
	// 	imageAlt: "concert photo",
	// 	description: "",
	// 	collection: "halfalive",
	// 	stats: "Samsung S22 Ultra • ",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["Concert"],
	// 	index: 0,
	// },
];

export default halfaliveArray;
