import { PhotoProps } from "@/types";

const halfaliveArray: PhotoProps[] = [
	{
		imageSrc: "/halfalive.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-3 md:col-span-2 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet.gif",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet3.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/tessaViolet4.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/mothermother.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/mothermother2.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/vundabar.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/vundabar2.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/phoebeBridgers.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/julienBaker.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
	{
		imageSrc: "/lucyDacus.jpg",
		imageAlt: "Perseid meteor shower 2024, one meteor visible",
		description: "",
		collection: "concerts",
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Concert"],
		index: 0,
	},
];

export default halfaliveArray;
