import { PhotoProps } from "@/types";

const mnArboretumArray: PhotoProps[] = [
	{
		imageSrc: "/mn-arboretum/mnArboretum20.JPG",
		imageAlt: "Faraway shot of the arboretum, showing bushes and trees in the distance",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/10000 • 33.33mm • ISO5000",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum18.JPG",
		imageAlt: "A pink rose",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/32000 • 29.1mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum19.JPG",
		imageAlt: "A salmon rose",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/10000 • 14.99mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum23.JPG",
		imageAlt: "Leaking faucet in front of pink flowers",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/4000 • 38.86mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum14.JPG",
		imageAlt: "Light pink sweet alyssum flowers",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 26.9mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum15.JPG",
		imageAlt: "Pink clethra flowers",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/11 • 1/1600 • 22.46mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum6.jpg",
		imageAlt:
			"Light hitting the bushes and trees from the back in a forest, with the silhouette of one tree in the foreground",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/5000 • 18.63mm • ISO5000",
		classAdjustments: "row-span-2 md:col-span-2 md:row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum22.JPG",
		imageAlt: "Statue of a mother and child in front of some pink flowers",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/1250 • 22.92mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum4.JPG",
		imageAlt: "Light shining on a yellow flower in the dark forest",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 44.38mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum16.JPG",
		imageAlt: "Trees shaded in the back of a field, with sky",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 46.09mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum5.JPG",
		imageAlt: "Light shining on a white flower in the dark forest",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/3.5 • 1/16000 • 13.29mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum2.JPG",
		imageAlt: "Yellow and purple flowers in the tall, shaded grass",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/4000 • 27.44mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum17.JPG",
		imageAlt: "Trees shaded in the back of a field, without sky",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/16000 • 46.09mm • ISO5000",
		classAdjustments: "row-span-2 md:col-span-2 md:row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum12.JPG",
		imageAlt: "Close-up of yellow thunbergias",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/11 • 1/4000 • 32.7mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum10.JPG",
		imageAlt: "Yellow and purple flowers in the grass in a field with trees in the background",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/5.6 • 1/4000 • 29.67mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum.JPG",
		imageAlt: "Yellow and purple flowers in the tall grass",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/8000 • 27.44mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum7.JPG",
		imageAlt: "Orange butterfly on a purple flower surrounded by black-eyed susans",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/4000 • 72mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum11.JPG",
		imageAlt: "Close-up of black-eyed susans",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/9 • 1/4000 • 10.38mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum8.JPG",
		imageAlt: "Black-eyed susan flowers lining the sidewalk",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/4000 • 14.12mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum3.JPG",
		imageAlt: "Yellow, white, and purple flowers in the tall grass",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/4000 • 27.44mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum9.JPG",
		imageAlt: "Yellow and purple flowers in the grass in a field",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/5 • 1/4000 • 34.64mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum13.JPG",
		imageAlt: "One yellow thunbergia in the leaves",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/4000 • 21.56mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum21.JPG",
		imageAlt: "Blue berries",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/1250 • 21.56mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnArboretum24.JPG",
		imageAlt: "Fountain with dripping water",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/8 • 1/4000 • 26.37mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden13.JPG",
		imageAlt: "Waterfall in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4 • 1/2500 • 15.28mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden2.JPG",
		imageAlt: "Close-up of moss-covered rocks in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/2.8 • 1/3200 • 9mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden4.JPG",
		imageAlt: "Japanese Garden house",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/2.8 • 1/3200 • 9mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden7.JPG",
		imageAlt: "White koi and orange koi with open mouth swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/3200 • 71.03mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden.JPG",
		imageAlt: "Moss-covered rocks in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/2.8 • 1/3200 • 9mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden8.JPG",
		imageAlt: "White koi and orange koi swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/3200 • 71.03mm • ISO5000",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden6.JPG",
		imageAlt: "A few koi with open mouths swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/3200 • 71.03mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden9.JPG",
		imageAlt: "Orange koi with open mouth in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/3200 • 71.03mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden5.JPG",
		imageAlt: "Several koi swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/3200 • 62.36mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden10.JPG",
		imageAlt: "Orange koi underwater with white koi in background",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/2500 • 21.12mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden11.JPG",
		imageAlt: "Koi swimming underwater, with one orange koi opening mouth above water",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/2500 • 19.84mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mn-arboretum/mnJapaneseGarden12.JPG",
		imageAlt: "Orange koi swimming underwater",
		description: "",
		collection: "mnArboretum",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/2500 • 45.23mm • ISO5000",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
];

export default mnArboretumArray;
