import { PhotoProps } from "@/types";

const mnArboretumArray: PhotoProps[] = [
	{
		imageSrc: "/mnArboretum20.JPG",
		imageAlt: "Faraway shot of the arboretum, showing bushes and trees in the distance",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum18.JPG",
		imageAlt: "A pink rose",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum19.JPG",
		imageAlt: "A salmon rose",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum23.JPG",
		imageAlt: "Leaking faucet in front of pink flowers",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum14.JPG",
		imageAlt: "Light pink sweet alyssum flowers",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum15.JPG",
		imageAlt: "Pink clethra flowers",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum6.jpg",
		imageAlt:
			"Light hitting the bushes and trees from the back in a forest, with the silhouette of one tree in the foreground",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "row-span-2 md:col-span-2 md:row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum22.JPG",
		imageAlt: "Statue of a mother and child in front of some pink flowers",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum4.JPG",
		imageAlt: "Light shining on a yellow flower in the dark forest",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum16.JPG",
		imageAlt: "Trees shaded in the back of a field, with sky",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum5.JPG",
		imageAlt: "Light shining on a white flower in the dark forest",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum2.JPG",
		imageAlt: "Yellow and purple flowers in the tall, shaded grass",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum17.JPG",
		imageAlt: "Trees shaded in the back of a field, without sky",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "row-span-2 md:col-span-2 md:row-span-2",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum12.JPG",
		imageAlt: "Close-up of yellow thunbergias",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum10.JPG",
		imageAlt: "Yellow and purple flowers in the grass in a field with trees in the background",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum.JPG",
		imageAlt: "Yellow and purple flowers in the tall grass",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum7.JPG",
		imageAlt: "Orange butterfly on a purple flower surrounded by black-eyed susans",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum11.JPG",
		imageAlt: "Close-up of black-eyed susans",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum8.JPG",
		imageAlt: "Black-eyed susan flowers lining the sidewalk",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum3.JPG",
		imageAlt: "Yellow, white, and purple flowers in the tall grass",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum9.JPG",
		imageAlt: "Yellow and purple flowers in the grass in a field",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum13.JPG",
		imageAlt: "One yellow thunbergia in the leaves",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum21.JPG",
		imageAlt: "Blue berries",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnArboretum24.JPG",
		imageAlt: "Fountain with dripping water",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden13.JPG",
		imageAlt: "Waterfall in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden2.JPG",
		imageAlt: "Close-up of moss-covered rocks in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden4.JPG",
		imageAlt: "Japanese Garden house",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden7.JPG",
		imageAlt: "White koi and orange koi with open mouth swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden.JPG",
		imageAlt: "Moss-covered rocks in the Japanese Garden",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden8.JPG",
		imageAlt: "White koi and orange koi swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden6.JPG",
		imageAlt: "A few koi with open mouths swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden9.JPG",
		imageAlt: "Orange koi with open mouth in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden5.JPG",
		imageAlt: "Several koi swimming in the pond",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden10.JPG",
		imageAlt: "Orange koi underwater with white koi in background",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden11.JPG",
		imageAlt: "Koi swimming underwater, with one orange koi opening mouth above water",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/mnJapaneseGarden12.JPG",
		imageAlt: "Orange koi swimming underwater",
		description: "",
		collection: "mnArboretum",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
];

export default mnArboretumArray;
