import { PhotoProps } from "@/types";

const montroseMoonriseArray: PhotoProps[] = [
	{
		imageSrc: "/montrose5.JPG",
		imageAlt: "Two people standing in front of a lighthouse at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 •  f/11 • 1/6400 • 24.84mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-3 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose6.JPG",
		imageAlt: "Two people in front of a lighthouse at Montrose Moonrise Vista Point, one is walking away",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/6400 • 31.46mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-3 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose11.JPG",
		imageAlt: "Five ducks swimming in front of a lighthouse at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 24.84mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose12.JPG",
		imageAlt: "A seagull lined up with a building on the Chicago skyline",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 33.98mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose7.JPG",
		imageAlt:
			"Far away shot of wwo people in front of a lighthouse at Montrose Moonrise Vista Point with boats in the horizon",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 9mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose3.JPG",
		imageAlt: "Duck in the water with the Chicago sklyine in the background",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/6400 • 33.98mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose9.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, medium distance",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 72mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose8.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, far away",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/5000 • 45.23mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose.JPG",
		imageAlt: "Two lighthouses visible at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/6400 • 9mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose14.JPG",
		imageAlt: "Lighthouse at Montrose Moonrise Vista Point, with boat passing by",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/6400 • 9mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose10.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, close up",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/10 • 1/5000 • 72mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
	{
		imageSrc: "/montrose2.JPG",
		imageAlt: "Rocks along the shore at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/11 • 1/6400 • 9mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/montrose4.JPG",
		imageAlt: "Mossy rocks in the water at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/4.5 • 1/6400 • 26.37mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Plants"],
		index: 0,
	},
	{
		imageSrc: "/montrose13.JPG",
		imageAlt: "Two ducks swimming across the water at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		stats: "SONY DSC-RX100M6 • f/6.3 • 1/10000 • 17.88mm • ISO2000",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
		index: 0,
	},
];

export default montroseMoonriseArray;
