interface PhotoModalProps {
	imageSrc: string;
	imageAlt: string;
	description: string;
	collection: string;
	showLink: boolean;
	stats: string;
	classAdjustments: string;
	tags?: string[];
}

const montroseMoonriseArray: PhotoModalProps[] = [
	{
		imageSrc: "/montrose5.JPG",
		imageAlt: "Two people standing in front of a lighthouse at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-3 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose6.JPG",
		imageAlt: "Two people in front of a lighthouse at Montrose Moonrise Vista Point, one is walking away",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-3 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose11.JPG",
		imageAlt: "Five ducks swimming in frnot of a lighthouse at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
	},
	{
		imageSrc: "/montrose12.JPG",
		imageAlt: "A seagull lined up with a building on the Chicago skyline",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
	},
	{
		imageSrc: "/montrose7.JPG",
		imageAlt:
			"Far away shot of wwo people in front of a lighthouse at Montrose Moonrise Vista Point with boats in the horizon",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose3.JPG",
		imageAlt: "Duck in the water with the Chicago sklyine in the background",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape", "Animals"],
	},
	{
		imageSrc: "/montrose9.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, medium distance",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/montrose8.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, far away",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/montrose.JPG",
		imageAlt: "Two lighthouses visible at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose14.JPG",
		imageAlt: "Lighthouse at Montrose Moonrise Vista Point, with boat passing by",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose10.JPG",
		imageAlt: "Duck in the water at Montrose Moonrise Vista Point, close up",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
	},
	{
		imageSrc: "/montrose2.JPG",
		imageAlt: "Rocks along the shore at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Landscape"],
	},
	{
		imageSrc: "/montrose4.JPG",
		imageAlt: "Mossy rocks in the water at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Plants"],
	},
	{
		imageSrc: "/montrose13.JPG",
		imageAlt: "Two ducks swimming across the water at Montrose Moonrise Vista Point",
		description: "",
		collection: "montroseMoonrise",
		showLink: false,
		stats: "SONY DSC-RX100M6",
		classAdjustments: "col-span-1 md:col-span-2 row-span-1",
		tags: ["Animals"],
	},
];

export default montroseMoonriseArray;
