import { PhotoProps } from "@/types";

const topsailBeachArray: PhotoProps[] = [
	// {
	// 	imageSrc: "/topsail-beach/beach.JPG",
	// 	imageAlt: "Shot of girl walking towards the ocean on Topsail Beach",
	// 	description: "",
	// 	collection: "topsailBeach",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["Landscape"],
	// 	index: 0,
	// },
	{
		imageSrc: "/topsail-beach/haSunset.JPG",
		imageAlt: "Shot of a man at the beach during sunset",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["People"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach2.JPG",
		imageAlt: "Shot of girl walking in the sand",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach3.JPG",
		imageAlt: "Shot of girl approaching the water at the beach",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	// {
	// 	imageSrc: "/topsail-beach/ham.jpg",
	// 	imageAlt: "Shot of girl approaching the water at the beach",
	// 	description: "",
	// 	collection: "topsailBeach",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["Landscape"],
	// 	index: 0,
	// },
	{
		imageSrc: "/topsail-beach/starryTSB3.JPG",
		imageAlt: "Shot of the night sky at Topsail Beach, with higher exposure",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/starryTSB.JPG",
		imageAlt: "Illuminated houses on Topsail Beach at night, with stars in the sky",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-2 row-span-2",
		tags: ["Landscape", "Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/starryTSB2.JPG",
		imageAlt: "Night shot of Topsail Beach",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/starryTSB4.JPG",
		imageAlt: "Shot of the night sky at Topsail Beach, with lower exposure",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/nightTSB.jpg",
		imageAlt: "Shot of two girls sitting on the beach under the moonlight",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
];

export default topsailBeachArray;
