import { PhotoProps } from "@/types";

const topsailTimelineArray: PhotoProps[] = [
	{
		imageSrc: "/topsail-timeline/timeline2.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/timeline.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/timeline7.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/timeline4.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/timeline5.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/timeline6.jpg",
		imageAlt: "",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/starryTSB3.JPG",
		imageAlt: "Shot of the night sky at Topsail Beach, with higher exposure",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/nightTSB.jpg",
		imageAlt: "Shot of two girls sitting on the beach under the moonlight",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/starryTSB.JPG",
		imageAlt: "Illuminated houses on Topsail Beach at night, with stars in the sky",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape", "Astrophotography"],
		index: 0,
	},
	{
		imageSrc: "/topsail-timeline/starryTSB4.JPG",
		imageAlt: "Shot of the night sky at Topsail Beach, with lower exposure",
		description: "",
		collection: "topsailTimeline",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Astrophotography"],
		index: 0,
	},
];

export default topsailTimelineArray;
