import { PhotoProps } from "@/types";

const topsailBeachArray: PhotoProps[] = [
	{
		imageSrc: "/topsail-beach/beach.JPG",
		imageAlt: "Shot of girl walking towards the ocean on Topsail Beach",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach2.JPG",
		imageAlt: "Shot of girl walking in the sand",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1 md:row-start-2",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/haSunset.JPG",
		imageAlt: "Shot of a man at the beach during sunset",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-2 col-start-2 row-start-1 row-span-2",
		tags: ["People"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach5.JPG",
		imageAlt: "Shot of two girls sitting in the water at the baech",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "col-span-1 row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach4.JPG",
		imageAlt: "Shot of beachfront homes",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "md:col-span-1 md:row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	{
		imageSrc: "/topsail-beach/beach3.JPG",
		imageAlt: "Shot of girl approaching the water at the beach",
		description: "",
		collection: "topsailBeach",
		stats: "",
		classAdjustments: "md:col-span-1 md:row-span-1",
		tags: ["Landscape"],
		index: 0,
	},
	// {
	// 	imageSrc: "/topsail-beach/ham.jpg",
	// 	imageAlt: "Shot of a man smiling at the beach",
	// 	description: "",
	// 	collection: "topsailBeach",
	// 	stats: "",
	// 	classAdjustments: "col-span-1 row-span-1",
	// 	tags: ["People"],
	// 	index: 0,
	// },
];

export default topsailBeachArray;
